---
title: "What is Reiki?"
theme: theme.css
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Reiki comes from the Japanese words “Rei” which means “Universal” and “Ki” which refers to the life force energy that flows through all of us and was brought through the enlightenment of Master Mikao Usui in the early 1900s. 

Universal Life Energy exists all around and in all of us, but can sometimes get “stuck” and cause spiritual, emotional, or physical ailments due to its inability to pass on after it no longer serves you.
 
That’s where I come in.

My name is Liam Horneker, and I am a certified Reiki Practitioner. I have training in channeling Reiki to identify and help clear any energetic blocks within your body. This treatment aims to restore balance in your mind, body, and spirit and accelerate healing by promoting total relaxation.

It is important to note that Reiki is a complementary therapy that should be employed alongside conventional medicine. The primary “risk” to Reiki comes in treating it as the entirety of your therapeutic practice rather than one aspect that can support your body and mind as you progress on your healing journey.

Think of it as though you had strep throat. While a spoonful of honey may help ease the pain and allow you to rest more easily, you also need antibiotics to clear up the underlying infection.

Similarly, while Reiki can do wonders in easing stress, anxiety, depression, (C)PTSD, and chronic pain (among other conditions), clients often report the greatest success when they pair reiki healing with other modalities such as conventional medicine and talk therapy sessions with a licensed mental health provider.

