---
title: "Reiki Lineage"
theme: theme.css
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

A Reiki lineage allows you to learn the training of your Reiki Practitioner and their degree of closeness to the origin of the practice. I am fortunate to know my Reiki lineage back to the start of the practice!

<div class="lineage">
**First Reiki Grand Master** \
**Dr. Mikao Usui** \
*who taught and attuned*

Reiki Grand Master \
**Dr. Chujiro Hayashi** \
*who taught and attuned*

Reiki Grand Master \
**Hawayo Takata** \
*who taught and attuned*

Reiki Master \
**Iris Ishikuro** \
*who taught and attuned*

Reiki Master \
**Arthur Robertson** \
*who taught and attuned*

Reiki Master \
**Sheldon Firth** \
*who taught and attuned*

Reiki Master \
**Jerry Anthony** \
*who taught and attuned*

Reiki Master \
**Dr. Helen Kelly** \
*who taught and attuned*

Reiki Master \
**Rev. Ilene Seveland** \
*who taught and attuned*

Reiki Master \
**Patsy Nelson** \
*who taught and attuned*

Reiki Master \
**Shelia DeShae Lamberson** \
*who taught and attuned*

Reiki Master \
**Ruth Ann Friend** \
*who taught and attuned*

Reiki Master \
**Lorie M. Allen** \
*who taught and attuned*

Reiki Practitioner \
**Liam M. Horneker**
</div>

